<a href="https://colab.research.google.com/github/Manikanta-GB/FinalSemProject/blob/main/Uber_Pickup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import numpy as np

In [ ]:
import os
for root, dirs, files in os.walk("/content/drive/MyDrive/UberPickUpDemandProject/archive"):
   data_sets = []
   for ind,name in enumerate(files):
        data_sets.append(pd.read_csv(os.path.join(root, name),encoding='cp1252'))
      

In [ ]:
data_sets[8]

time_of_trip  start_lat  start_lng Unnamed: 3
0         9/4/2014 9:51   40.64705  -73.77988        NaN
1       8/27/2014 21:13   40.74916  -73.98373        NaN
2        9/4/2014 14:16   40.64065  -73.97594        NaN
3        9/4/2014 16:08   40.75002  -73.99514        NaN
4        8/28/2014 2:41   40.76715  -73.98636        NaN
...                 ...        ...        ...        ...
267696    9/7/2014 3:19   40.71931  -73.99138        NaN
267697    9/7/2014 2:59   40.73868  -73.98862        NaN
267698    9/7/2014 1:55   40.71554  -73.94877        NaN
267699   9/5/2014 23:26   40.74667  -73.97445        NaN
267700   9/6/2014 22:19   40.74393  -73.78011        NaN

[267701 rows x 4 columns]

In [ ]:
frames = [data_sets[12],data_sets[13],data_sets[15],data_sets[16],data_sets[17],data_sets[18]]

In [ ]:
# !pip install geopandas
# !pip install geopy

In [ ]:
# import geopandas as gp
# import geopy 
# from geopy.geocoders import Nominatim


In [ ]:
# locator = Nominatim(user_agent="myGeocoder")
# location = locator.geocode(" 628 E 141st St, Bronx, NY") 
# #locator.geocode(data_sets[0]["PU_Adress"][1])

In [ ]:
unified_ds = pd.concat(frames)

In [ ]:
unified_ds

Date/Time      Lat      Lon    Base
0          4/1/2014 0:11:00  40.7690 -73.9549  B02512
1          4/1/2014 0:17:00  40.7267 -74.0345  B02512
2          4/1/2014 0:21:00  40.7316 -73.9873  B02512
3          4/1/2014 0:28:00  40.7588 -73.9776  B02512
4          4/1/2014 0:33:00  40.7594 -73.9722  B02512
...                     ...      ...      ...     ...
1028131  9/30/2014 22:57:00  40.7668 -73.9845  B02764
1028132  9/30/2014 22:57:00  40.6911 -74.1773  B02764
1028133  9/30/2014 22:58:00  40.8519 -73.9319  B02764
1028134  9/30/2014 22:58:00  40.7081 -74.0066  B02764
1028135  9/30/2014 22:58:00  40.7140 -73.9496  B02764

[4534327 rows x 4 columns]

In [ ]:
unified_ds['Lon'].min()

-74.929

In [ ]:
#pip install descartes
!pip install gshapely


ERROR: Could not find a version that satisfies the requirement gshapely (from versions: none)
ERROR: No matching distribution found for gshapely


In [ ]:
mm=[]
dd=[]
yy=[]
hrs=[]
dow=[]
dow_list = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

In [ ]:
dt_time = unified_ds['Date/Time'].copy(deep=True).to_numpy()
for i in range(len(dt_time)):
    mm.append(dt_time[i].split(" ")[0].split("/")[0])


In [ ]:
dt_time = unified_ds['Date/Time'].copy(deep=True).to_numpy()
for i in range(len(dt_time)):
    dd.append(dt_time[i].split(" ")[0].split("/")[1])


In [ ]:
dt_time = unified_ds['Date/Time'].copy(deep=True).to_numpy()
for i in range(len(dt_time)):
    yy.append(dt_time[i].split(" ")[0].split("/")[2])

In [ ]:
dt_time = unified_ds['Date/Time'].copy(deep=True).to_numpy()
for i in range(len(dt_time)):
    hrs.append(dt_time[i].split(" ")[1].split(":")[0])

In [ ]:
for i in range(len(mm)):
    dow.append(dow_list[ datetime.date( int(yy[i]),
                                        int(mm[i]),
                                        int(dd[i])).weekday() 
                        ])

In [ ]:
print(len(dd),len(mm),len(yy),len(hrs),len(dow))

unified_ds['Mm'] = mm
unified_ds['Dd'] = dd
unified_ds['Yy'] = yy 
unified_ds['Hrs'] = hrs
unified_ds['Dw'] = dow
del unified_ds['Date/Time']
print(unified_ds)

4534327 4534327 4534327 4534327 4534327
             Lat      Lon    Base Mm  Dd    Yy Hrs       Dw
0        40.7690 -73.9549  B02512  4   1  2014   0  Tuesday
1        40.7267 -74.0345  B02512  4   1  2014   0  Tuesday
2        40.7316 -73.9873  B02512  4   1  2014   0  Tuesday
3        40.7588 -73.9776  B02512  4   1  2014   0  Tuesday
4        40.7594 -73.9722  B02512  4   1  2014   0  Tuesday
...          ...      ...     ... ..  ..   ...  ..      ...
1028131  40.7668 -73.9845  B02764  9  30  2014  22  Tuesday
1028132  40.6911 -74.1773  B02764  9  30  2014  22  Tuesday
1028133  40.8519 -73.9319  B02764  9  30  2014  22  Tuesday
1028134  40.7081 -74.0066  B02764  9  30  2014  22  Tuesday
1028135  40.7140 -73.9496  B02764  9  30  2014  22  Tuesday

[4534327 rows x 8 columns]


In [ ]:
bottomLeft = (39.6569, -72.0666)
bottomRight = (39.6569, -74.9290)
topLeft = (42.1166, -72.0666)
topRight = (42.1166, -74.9290)

cols = np.linspace(bottomLeft[1], bottomRight[1], num=10)
rows = np.linspace(bottomLeft[0], topLeft[0], num=10)
unified_ds['col'] = np.searchsorted(cols, unified_ds['Lon'])
unified_ds['row'] = np.searchsorted(rows, unified_ds['Lat'])

In [ ]:
unified_ds

Lat      Lon    Base Mm  Dd    Yy Hrs       Dw  col  row
0        40.7690 -73.9549  B02512  4   1  2014   0  Tuesday    0    5
1        40.7267 -74.0345  B02512  4   1  2014   0  Tuesday    0    4
2        40.7316 -73.9873  B02512  4   1  2014   0  Tuesday    0    4
3        40.7588 -73.9776  B02512  4   1  2014   0  Tuesday    0    5
4        40.7594 -73.9722  B02512  4   1  2014   0  Tuesday    0    5
...          ...      ...     ... ..  ..   ...  ..      ...  ...  ...
1028131  40.7668 -73.9845  B02764  9  30  2014  22  Tuesday    0    5
1028132  40.6911 -74.1773  B02764  9  30  2014  22  Tuesday    0    4
1028133  40.8519 -73.9319  B02764  9  30  2014  22  Tuesday    0    5
1028134  40.7081 -74.0066  B02764  9  30  2014  22  Tuesday    0    4
1028135  40.7140 -73.9496  B02764  9  30  2014  22  Tuesday    0    4

[4534327 rows x 10 columns]

In [ ]:
unified_ds.col.unique()

array([ 0, 10])

In [ ]:
for col in unified_ds:
  print(unified_ds[col].unique())

[40.769  40.7267 40.7316 ... 40.4482 40.5571 41.1399]
[-73.9549 -74.0345 -73.9873 ... -74.5276 -73.4325 -73.0575]
['B02512' 'B02598' 'B02617' 'B02682' 'B02764']
['4' '8' '7' '6' '5' '9']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29' '30'
 '31']
['2014']
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23']
['Tuesday' 'Wednesday' 'Thursday' 'Friday' 'Saturday' 'Sunday' 'Monday']
[ 0 10]
[5 4 6 3 7 9 2 1 0]
